### ISSUE TITLE
Downloading Janelia FlyEM Hemibrain Meshes

### ISSUE THREAD

**Issue by schlegelp** [seung-lab/cloud-volume#337]
Hi William,

Quick question. I'm trying to fetch meshes from the hemibrain dataset but run into missing manifest errors.

```Python

In [56]: vol = CloudVolume('precomputed://gs://neuroglancer-janelia-flyem-hemibrain/segmentation_52a13', fill_missing=True)                     

In [57]: vol.mesh.get(5812983825)                                                                                                                                       
Existence Testing:   0%|                                                                                                                        | 0/20 [00:00<?, ?it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-57-33c7de7a6bd8> in <module>
----> 1 vol.mesh.get(5812983825)

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/mesh/unsharded.py in get(self, segids, remove_duplicate_vertices, fuse, chunk_size)
    119       raise ValueError(red(
    120         'Segment ID(s) {} are missing corresponding mesh manifests.\nAborted.' \
--> 121         .format(missing)
    122       ))
    123 

ValueError: Segment ID(s) 5812983825 are missing corresponding mesh manifests.
Aborted.
```

This exemplary mesh definitely exists - see this neuroglancer config:
```Python
{
  "dimensions": {
    "x": [
      8e-9,
      "m"
    ],
    "y": [
      8e-9,
      "m"
    ],
    "z": [
      8e-9,
      "m"
    ]
  },
  "position": [
    18824.90234375,
    25317.96875,
    26495.2421875
  ],
  "crossSectionScale": 1,
  "projectionOrientation": [
    -0.36361587047576904,
    -0.015047410503029823,
    -0.4325231611728668,
    0.8249126076698303
  ],
  "projectionScale": 983.7572106361007,
  "layers": [
    {
      "type": "image",
      "source": {
        "url": "precomputed://gs://neuroglancer-janelia-flyem-hemibrain/emdata/clahe_yz/jpeg"
      },
      "tab": "source",
      "blend": "default",
      "name": "hemibrain:v1.0.1-grayscalejpeg"
    },
    {
      "type": "segmentation",
      "source": {
        "url": "precomputed://gs://neuroglancer-janelia-flyem-hemibrain/segmentation_52a13"
      },
      "tab": "source",
      "segments": [
        "5812983825"
      ],
      "skeletonRendering": {
        "mode2d": "lines_and_points",
        "mode3d": "lines"
      },
      "name": "hemibrain:v1.0.1"
    },
    {
      "type": "annotation",
      "source": {
        "url": "dvid://https://hemibrain-dvid.janelia.org/61c8/public_annotations?usertag=true&auth=https://hemibrain-dvid.janelia.org/api/server/token"
      },
      "tab": "source",
      "tool": "annotatePoint",
      "annotationColor": "#ff0000",
      "shader": "#uicontrol vec3 falseSplitColor color(default=\"#F08040\")\n#uicontrol vec3 falseMergeColor color(default=\"#F040F0\")\n#uicontrol vec3 checkedColor color(default=\"green\")\n#uicontrol vec3 borderColor color(default=\"black\")\n\n#uicontrol float radius slider(min=3, max=20, step=1, default=10)\n#uicontrol float opacity slider(min=0, max=1, step=0.1, default=1)  \n\nvoid main() {\n  setPointMarkerSize(radius);\n  float finalOpacity = PROJECTION_VIEW ? opacity * 0.2 : opacity;\n\n  setPointMarkerBorderColor(vec4(borderColor, finalOpacity));\n  if (prop_rendering_attribute() == 1) {\n    setColor(vec4(checkedColor, finalOpacity));\n  } else if (prop_rendering_attribute() == 2) {    \n    setColor(vec4(falseSplitColor, finalOpacity));\n  } else if (prop_rendering_attribute() == 3)  {\n    setColor(vec4(falseMergeColor, finalOpacity));\n  } else {\n setColor(vec4(1, 0, 0, finalOpacity));\n  }\n}",
      "name": "hemibrain:v1.0.1-public_annotations",
      "visible": false
    },
    {
      "type": "annotation",
      "source": {
        "url": "precomputed://gs://neuroglancer-janelia-flyem-hemibrain/synapses_52a13"
      },
      "tab": "source",
      "shader": "#uicontrol vec3 preColor color(default=\"yellow\")\n#uicontrol vec3 postColor color(default=\"gray\")\n#uicontrol float preConfidence slider(min=0, max=1, default=0)\n#uicontrol float postConfidence slider(min=0, max=1, default=0)\n#uicontrol float sliceViewOpacity slider(min=0, max=1, default=0.5)\n#uicontrol float projectionViewOpacity slider(min=0, max=1, default=0.3)\n\nvoid main() {\n  float opacity = PROJECTION_VIEW ? projectionViewOpacity : sliceViewOpacity;\n  setColor(vec4(defaultColor(), opacity));\n  setEndpointMarkerColor(\n    vec4(preColor, opacity),\n    vec4(postColor, opacity));\n  setEndpointMarkerBorderColor(\n    vec4(0, 0, 0, opacity),\n    vec4(0, 0, 0,     opacity)\n  );\n\n  setEndpointMarkerSize(5.0, 5.0);\n  setLineWidth(2.0);\n  if (prop_pre_synaptic_confidence()< preConfidence ||\n  prop_post_synaptic_confidence()< postConfidence) discard;\n}\n",
      "linkedSegmentationLayer": {
        "pre_synaptic_cell": "hemibrain:v1.0.1",
        "post_synaptic_cell": "hemibrain:v1.0.1"
      },
      "filterBySegmentation": [
        "post_synaptic_cell",
        "pre_synaptic_cell"
      ],
      "name": "hemibrain:v1.0.1-synapses",
      "visible": false
    }
  ],
  "layout": "xy-3d"
}
```

I've been trying to dig into possible issues myself but came up empty-handed. Any pointers would be very much appreciated.

**Comment by william-silversmith** [comment]
Hi Philipp,

Unfortunately, that mesh volume is using the multi-LOD sharded format which is currently unsupported... :-/ I'm planning on supporting these meshes but have been occupied with some other work related to our proofreading format `graphene` at the moment. I'm happy to accept contributions if someone wants to work on it. (For anyone interested, please let me know before you start work in case I've spontaneously started.) 

I'll add a better error message for this problem in the next release.

Related Issue #267

**Comment by perlman** [comment]
I'm working on this with #340.

**Comment by schlegelp** [comment]
Works like a charm now, thanks! I found a small bug with the error message when trying to fetch an lod that's not available (Not sure if this is already fixed - I'm on `1.18.0`):
```Python
vol = CloudVolume('precomputed://gs://neuroglancer-janelia-flyem-hemibrain/segmentation_52a13', fill_missing=True) 
m = vol.mesh.get(733316908, lod=4)                                                                                                                             
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-31-c6ae5fbff95a> in <module>
----> 1 m = vol.mesh.get(733316908, lod=4)

~/.local/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/mesh/multilod.py in get(self, segids, lod, concat, progress)
    104       if lod >= manifest.num_lods:
    105         raise exceptions.MeshDecodeError(red(
--> 106           'LOD value out of range ({} > {}) for segment {}.'.format(max(lods), manifest.num_lods, segid)
    107         ))
    108 

NameError: name 'lods' is not defined
```

**Comment by perlman** [comment]
Not yet fixed. :)

I can tackle this today (it's just a few characters) & add a test.  (This comes from my indecisiveness on how to request which lod.)

**Comment by william-silversmith** [comment]
Closing since it seems like this is fixed. Thanks again Eric!
